name: Build images
on:
  workflow_dispatch:
  schedule:
    # At 00:00 on Saturday.
    - cron: "0 0 * * 6"
    - cron: "*/15 * * * *"
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    strategy:
      matrix:
        include:
          - directory: jupyter
            dockerfile: ubuntu-pybind11

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      -
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.directory }}/${{ matrix.dockerfile }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.directory }}
          file: ${{ matrix.directory }}/${{ matrix.dockerfile }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
