name: Build images
on:
#  create
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"  # At 00:00 on Saturday.
    - cron: "*/15 * * * *"
#  push:
#    branches: [ main, master ]
#    tags: "*"
  # https://stackoverflow.com/questions/60418323/triggering-a-new-workflow-from-another-workflow
#  workflow_run:
#    workflows: [ "Bump version" ]
#    types:
#      - completed
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"
  create:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - directory: jupyter
            dockerfile: ubuntu-pybind
          - directory: jupyter
            dockerfile: ubuntu-pip
          - directory: jupyter
            dockerfile: xeus-cling

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      -
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.directory }}/${{ matrix.dockerfile }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          #  type=sha,format=long
      -
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      -
#        run: |
#          echo ${{ steps.meta.outputs.tags }}
#          echo ${{ steps.meta.outputs.labels }}
      -
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.directory }}
          file: ${{ matrix.directory }}/${{ matrix.dockerfile }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
