# example 1: on push to master
name: Bump version
on:
  push:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: '0'
      -
        #uses: anothrNick/github-tag-action@1
        uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: main,master
          with-v: true
