# example 1: on push to master
name: Bump version
on:
  push:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      -
        #uses: anothrNick/github-tag-action@1
        uses: phish108/autotag-action@v1.1.55
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main,master
          WITH_V: true
