name: Bump version
on:
  push:
    branches: [ main, master ]

env:
  # Enable color output for utils (e.g. pip, conan, cmake, etc.)
  TERM: ANSI
  CLICOLOR_FORCE: 1

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      -
        #uses: anothrNick/github-tag-action@1
        uses: phish108/autotag-action@v1.1.64
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: main,master
          with-v: true
          dry-run: true
      -
        continue-on-error: true
        run: |
          echo "${{ steps.tagger.outputs.new-tag }}" > VERSION.txt
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "version bump to ${{ steps.tagger.outputs.new-tag }}"
      -
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      -
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          release-branch: main,master
          with-v: true
